### ISSUE TITLE
Displacements (of Source): Not Linked?

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#64]

**Comment by capitanevs** [comment]
The longitudinal displacement of the source seems not to be linked.
Is is true?
Below: should be -10, is 0
![immagine](https://user-images.githubusercontent.com/13431660/133631891-60039cff-4f22-40d9-a660-c87c5dc0c8aa.png)
![immagine](https://user-images.githubusercontent.com/13431660/133632009-4d1487f4-bb64-4334-ab93-97e0b1defed7.png)

**Comment by aljosahafner** [comment]
I will check, thanks!

**Comment by aljosahafner** [comment]
In fact we have never tried small displacements and they should be correctly implemented for `OWOpticalElement`, but source is not inheriting from this class. I implemented it now, but it does not print correctly... Latest version includes these corrections, so you can test it.

![image](https://user-images.githubusercontent.com/51963146/133741111-f35bddea-6783-4b02-b8a9-b0d53fe6f2c4.png)

**Comment by capitanevs** [comment]
Ok thamks.
I will check
Beware: the print function for a beamline does not write about the small displacements.
Perhaps the print for OpticalElement does (but I am still not sure:)

--
Inviato da myMail per Android Venerdì, 17 Settembre 2021, 09:18AM +02:00 da aljosahafner  ***@***.*** :

**Comment by capitanevs** [comment]
Ok, it works.

this the versin of the file I used

[Wiser Snippets In Oasys.log](https://github.com/oasys-elettra-kit/OASYS1-Wiser/files/7184760/Wiser.Snippets.In.Oasys.log)
